[default]
optimizer = true
optimizer_runs = 200
lib-paths = "node_modules"
contracts = "contracts"
fuzz_max_global_rejects = 1000000
fuzz_max_local_rejects = 1000000
fuzz_runs = 50000

[ci]
verbosity = 3