networks:
    development:
        gas_limit: max
        gas_buffer: 1
        gas_price: 0
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings:
            port: 8545
            gas_limit: 8000000
            accounts: 1000
            chain_id: 1337
            network_id: 1588949648
            evm_version: istanbul
            mnemonic: brownie
            block_time: 0
            default_balance: 1000000

compiler:
    solc:
        optimizer:
            enabled: true
            runs: 200
        remappings:
          - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.3.0"