ignore:
  - "**/config/**"
  - "**/contracts/interfaces/**"
  - "**/contracts/mocks/**"
  - "**/contracts/test/**"
  - "**/contracts/Math.sol"
  - "**/existingContracts/**"
  - "**/lib/**"
  - "**/scripts/**"
  - "**/test/**"
  - "**/utils/**"