[profile.default]
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
# remappings = [
#     '@chainlink/=node_modules/@chainlink/',
#     '@ensdomains/=node_modules/@ensdomains/',
#     '@openzeppelin/=node_modules/@openzeppelin/',
#     '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
#     '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
#     '@uniswap/=node_modules/@uniswap/',
#     '@uniswap/v3-core=node_modules/@uniswap/v3-core/',
#     '@uniswap/v3-periphery/=node_modules/@uniswap/v3-periphery/',
#     'base64-sol/=node_modules/base64-sol/',
#     'contracts/=node_modules/@uniswap/lib/contracts/',
#     'eth-gas-reporter/=node_modules/eth-gas-reporter/',
#     'hardhat-deploy/=node_modules/hardhat-deploy/',
#     'hardhat/=node_modules/hardhat/',
# ]

# do not fork by default
# eth-rpc-url = "https://eth-mainnet.alchemyapi.io/v2/snGskhAXMQaRLnJaxbcfOL7U5_bSZl_Y"
# fork-block-number = 14546456

fuzz_runs = 500

# See more config options https://github.com/gakonst/foundry/tree/master/config
